// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberFindByNationalCode.proto

package com.motaharinia.client.project.modules.member.rpc.stub.findbyid;

public interface MemberReadByIdRequestDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MemberReadByIdRequestDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
