// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberFindByNationalCode.proto

package com.motaharinia.client.project.modules.member.rpc.stub.findbyid;

public interface MemberResponseDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MemberResponseDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   * @return The responseCode.
   */
  int getResponseCode();

  /**
   * <code>int64 id = 3;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string firstName = 4;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 4;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 5;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 5;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string nationalCode = 6;</code>
   * @return The nationalCode.
   */
  java.lang.String getNationalCode();
  /**
   * <code>string nationalCode = 6;</code>
   * @return The bytes for nationalCode.
   */
  com.google.protobuf.ByteString
      getNationalCodeBytes();

  /**
   * <code>int64 dateOfBirth = 7;</code>
   * @return The dateOfBirth.
   */
  long getDateOfBirth();

  /**
   * <code>int64 createAt = 8;</code>
   * @return The createAt.
   */
  long getCreateAt();

  /**
   * <code>int64 updateAt = 9;</code>
   * @return The updateAt.
   */
  long getUpdateAt();

  /**
   * <code>bool invalid = 10;</code>
   * @return The invalid.
   */
  boolean getInvalid();

  /**
   * <code>bool hidden = 11;</code>
   * @return The hidden.
   */
  boolean getHidden();
}
