// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberFindByNationalCode.proto

package com.motaharinia.client.project.modules.member.rpc.stub.findbyid;

/**
 * Protobuf type {@code MemberResponseDto}
 */
public  final class MemberResponseDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MemberResponseDto)
    MemberResponseDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MemberResponseDto.newBuilder() to construct.
  private MemberResponseDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MemberResponseDto() {
    responseMessage_ = "";
    firstName_ = "";
    lastName_ = "";
    nationalCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MemberResponseDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MemberResponseDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            responseMessage_ = s;
            break;
          }
          case 16: {

            responseCode_ = input.readInt32();
            break;
          }
          case 24: {

            id_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            firstName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            lastName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            nationalCode_ = s;
            break;
          }
          case 56: {

            dateOfBirth_ = input.readInt64();
            break;
          }
          case 64: {

            createAt_ = input.readInt64();
            break;
          }
          case 72: {

            updateAt_ = input.readInt64();
            break;
          }
          case 80: {

            invalid_ = input.readBool();
            break;
          }
          case 88: {

            hidden_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberFindByIdProto.internal_static_MemberResponseDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberFindByIdProto.internal_static_MemberResponseDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto.class, com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto.Builder.class);
  }

  public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object responseMessage_;
  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  public java.lang.String getResponseMessage() {
    java.lang.Object ref = responseMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  public com.google.protobuf.ByteString
      getResponseMessageBytes() {
    java.lang.Object ref = responseMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSECODE_FIELD_NUMBER = 2;
  private int responseCode_;
  /**
   * <code>int32 responseCode = 2;</code>
   * @return The responseCode.
   */
  public int getResponseCode() {
    return responseCode_;
  }

  public static final int ID_FIELD_NUMBER = 3;
  private long id_;
  /**
   * <code>int64 id = 3;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object firstName_;
  /**
   * <code>string firstName = 4;</code>
   * @return The firstName.
   */
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string firstName = 4;</code>
   * @return The bytes for firstName.
   */
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object lastName_;
  /**
   * <code>string lastName = 5;</code>
   * @return The lastName.
   */
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>string lastName = 5;</code>
   * @return The bytes for lastName.
   */
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NATIONALCODE_FIELD_NUMBER = 6;
  private volatile java.lang.Object nationalCode_;
  /**
   * <code>string nationalCode = 6;</code>
   * @return The nationalCode.
   */
  public java.lang.String getNationalCode() {
    java.lang.Object ref = nationalCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nationalCode_ = s;
      return s;
    }
  }
  /**
   * <code>string nationalCode = 6;</code>
   * @return The bytes for nationalCode.
   */
  public com.google.protobuf.ByteString
      getNationalCodeBytes() {
    java.lang.Object ref = nationalCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nationalCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATEOFBIRTH_FIELD_NUMBER = 7;
  private long dateOfBirth_;
  /**
   * <code>int64 dateOfBirth = 7;</code>
   * @return The dateOfBirth.
   */
  public long getDateOfBirth() {
    return dateOfBirth_;
  }

  public static final int CREATEAT_FIELD_NUMBER = 8;
  private long createAt_;
  /**
   * <code>int64 createAt = 8;</code>
   * @return The createAt.
   */
  public long getCreateAt() {
    return createAt_;
  }

  public static final int UPDATEAT_FIELD_NUMBER = 9;
  private long updateAt_;
  /**
   * <code>int64 updateAt = 9;</code>
   * @return The updateAt.
   */
  public long getUpdateAt() {
    return updateAt_;
  }

  public static final int INVALID_FIELD_NUMBER = 10;
  private boolean invalid_;
  /**
   * <code>bool invalid = 10;</code>
   * @return The invalid.
   */
  public boolean getInvalid() {
    return invalid_;
  }

  public static final int HIDDEN_FIELD_NUMBER = 11;
  private boolean hidden_;
  /**
   * <code>bool hidden = 11;</code>
   * @return The hidden.
   */
  public boolean getHidden() {
    return hidden_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getResponseMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseMessage_);
    }
    if (responseCode_ != 0) {
      output.writeInt32(2, responseCode_);
    }
    if (id_ != 0L) {
      output.writeInt64(3, id_);
    }
    if (!getFirstNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, firstName_);
    }
    if (!getLastNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, lastName_);
    }
    if (!getNationalCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, nationalCode_);
    }
    if (dateOfBirth_ != 0L) {
      output.writeInt64(7, dateOfBirth_);
    }
    if (createAt_ != 0L) {
      output.writeInt64(8, createAt_);
    }
    if (updateAt_ != 0L) {
      output.writeInt64(9, updateAt_);
    }
    if (invalid_ != false) {
      output.writeBool(10, invalid_);
    }
    if (hidden_ != false) {
      output.writeBool(11, hidden_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getResponseMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseMessage_);
    }
    if (responseCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, responseCode_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, id_);
    }
    if (!getFirstNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, firstName_);
    }
    if (!getLastNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, lastName_);
    }
    if (!getNationalCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, nationalCode_);
    }
    if (dateOfBirth_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, dateOfBirth_);
    }
    if (createAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, createAt_);
    }
    if (updateAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, updateAt_);
    }
    if (invalid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, invalid_);
    }
    if (hidden_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, hidden_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto)) {
      return super.equals(obj);
    }
    com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto other = (com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto) obj;

    if (!getResponseMessage()
        .equals(other.getResponseMessage())) return false;
    if (getResponseCode()
        != other.getResponseCode()) return false;
    if (getId()
        != other.getId()) return false;
    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (!getNationalCode()
        .equals(other.getNationalCode())) return false;
    if (getDateOfBirth()
        != other.getDateOfBirth()) return false;
    if (getCreateAt()
        != other.getCreateAt()) return false;
    if (getUpdateAt()
        != other.getUpdateAt()) return false;
    if (getInvalid()
        != other.getInvalid()) return false;
    if (getHidden()
        != other.getHidden()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getResponseMessage().hashCode();
    hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
    hash = (53 * hash) + getResponseCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + NATIONALCODE_FIELD_NUMBER;
    hash = (53 * hash) + getNationalCode().hashCode();
    hash = (37 * hash) + DATEOFBIRTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDateOfBirth());
    hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateAt());
    hash = (37 * hash) + UPDATEAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdateAt());
    hash = (37 * hash) + INVALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInvalid());
    hash = (37 * hash) + HIDDEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHidden());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MemberResponseDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MemberResponseDto)
      com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberFindByIdProto.internal_static_MemberResponseDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberFindByIdProto.internal_static_MemberResponseDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto.class, com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto.Builder.class);
    }

    // Construct using com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseMessage_ = "";

      responseCode_ = 0;

      id_ = 0L;

      firstName_ = "";

      lastName_ = "";

      nationalCode_ = "";

      dateOfBirth_ = 0L;

      createAt_ = 0L;

      updateAt_ = 0L;

      invalid_ = false;

      hidden_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberFindByIdProto.internal_static_MemberResponseDto_descriptor;
    }

    @java.lang.Override
    public com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto getDefaultInstanceForType() {
      return com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto.getDefaultInstance();
    }

    @java.lang.Override
    public com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto build() {
      com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto buildPartial() {
      com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto result = new com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto(this);
      result.responseMessage_ = responseMessage_;
      result.responseCode_ = responseCode_;
      result.id_ = id_;
      result.firstName_ = firstName_;
      result.lastName_ = lastName_;
      result.nationalCode_ = nationalCode_;
      result.dateOfBirth_ = dateOfBirth_;
      result.createAt_ = createAt_;
      result.updateAt_ = updateAt_;
      result.invalid_ = invalid_;
      result.hidden_ = hidden_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto) {
        return mergeFrom((com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto other) {
      if (other == com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto.getDefaultInstance()) return this;
      if (!other.getResponseMessage().isEmpty()) {
        responseMessage_ = other.responseMessage_;
        onChanged();
      }
      if (other.getResponseCode() != 0) {
        setResponseCode(other.getResponseCode());
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        onChanged();
      }
      if (!other.getNationalCode().isEmpty()) {
        nationalCode_ = other.nationalCode_;
        onChanged();
      }
      if (other.getDateOfBirth() != 0L) {
        setDateOfBirth(other.getDateOfBirth());
      }
      if (other.getCreateAt() != 0L) {
        setCreateAt(other.getCreateAt());
      }
      if (other.getUpdateAt() != 0L) {
        setUpdateAt(other.getUpdateAt());
      }
      if (other.getInvalid() != false) {
        setInvalid(other.getInvalid());
      }
      if (other.getHidden() != false) {
        setHidden(other.getHidden());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object responseMessage_ = "";
    /**
     * <code>string responseMessage = 1;</code>
     * @return The responseMessage.
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string responseMessage = 1;</code>
     * @return The bytes for responseMessage.
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string responseMessage = 1;</code>
     * @param value The responseMessage to set.
     * @return This builder for chaining.
     */
    public Builder setResponseMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      responseMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string responseMessage = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseMessage() {
      
      responseMessage_ = getDefaultInstance().getResponseMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string responseMessage = 1;</code>
     * @param value The bytes for responseMessage to set.
     * @return This builder for chaining.
     */
    public Builder setResponseMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      responseMessage_ = value;
      onChanged();
      return this;
    }

    private int responseCode_ ;
    /**
     * <code>int32 responseCode = 2;</code>
     * @return The responseCode.
     */
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>int32 responseCode = 2;</code>
     * @param value The responseCode to set.
     * @return This builder for chaining.
     */
    public Builder setResponseCode(int value) {
      
      responseCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responseCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseCode() {
      
      responseCode_ = 0;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 3;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 4;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firstName = 4;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firstName = 4;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 4;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>string lastName = 5;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastName = 5;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastName = 5;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 5;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nationalCode_ = "";
    /**
     * <code>string nationalCode = 6;</code>
     * @return The nationalCode.
     */
    public java.lang.String getNationalCode() {
      java.lang.Object ref = nationalCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nationalCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nationalCode = 6;</code>
     * @return The bytes for nationalCode.
     */
    public com.google.protobuf.ByteString
        getNationalCodeBytes() {
      java.lang.Object ref = nationalCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nationalCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nationalCode = 6;</code>
     * @param value The nationalCode to set.
     * @return This builder for chaining.
     */
    public Builder setNationalCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nationalCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nationalCode = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNationalCode() {
      
      nationalCode_ = getDefaultInstance().getNationalCode();
      onChanged();
      return this;
    }
    /**
     * <code>string nationalCode = 6;</code>
     * @param value The bytes for nationalCode to set.
     * @return This builder for chaining.
     */
    public Builder setNationalCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nationalCode_ = value;
      onChanged();
      return this;
    }

    private long dateOfBirth_ ;
    /**
     * <code>int64 dateOfBirth = 7;</code>
     * @return The dateOfBirth.
     */
    public long getDateOfBirth() {
      return dateOfBirth_;
    }
    /**
     * <code>int64 dateOfBirth = 7;</code>
     * @param value The dateOfBirth to set.
     * @return This builder for chaining.
     */
    public Builder setDateOfBirth(long value) {
      
      dateOfBirth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 dateOfBirth = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateOfBirth() {
      
      dateOfBirth_ = 0L;
      onChanged();
      return this;
    }

    private long createAt_ ;
    /**
     * <code>int64 createAt = 8;</code>
     * @return The createAt.
     */
    public long getCreateAt() {
      return createAt_;
    }
    /**
     * <code>int64 createAt = 8;</code>
     * @param value The createAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreateAt(long value) {
      
      createAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 createAt = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateAt() {
      
      createAt_ = 0L;
      onChanged();
      return this;
    }

    private long updateAt_ ;
    /**
     * <code>int64 updateAt = 9;</code>
     * @return The updateAt.
     */
    public long getUpdateAt() {
      return updateAt_;
    }
    /**
     * <code>int64 updateAt = 9;</code>
     * @param value The updateAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateAt(long value) {
      
      updateAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 updateAt = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateAt() {
      
      updateAt_ = 0L;
      onChanged();
      return this;
    }

    private boolean invalid_ ;
    /**
     * <code>bool invalid = 10;</code>
     * @return The invalid.
     */
    public boolean getInvalid() {
      return invalid_;
    }
    /**
     * <code>bool invalid = 10;</code>
     * @param value The invalid to set.
     * @return This builder for chaining.
     */
    public Builder setInvalid(boolean value) {
      
      invalid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool invalid = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvalid() {
      
      invalid_ = false;
      onChanged();
      return this;
    }

    private boolean hidden_ ;
    /**
     * <code>bool hidden = 11;</code>
     * @return The hidden.
     */
    public boolean getHidden() {
      return hidden_;
    }
    /**
     * <code>bool hidden = 11;</code>
     * @param value The hidden to set.
     * @return This builder for chaining.
     */
    public Builder setHidden(boolean value) {
      
      hidden_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hidden = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearHidden() {
      
      hidden_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MemberResponseDto)
  }

  // @@protoc_insertion_point(class_scope:MemberResponseDto)
  private static final com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto();
  }

  public static com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MemberResponseDto>
      PARSER = new com.google.protobuf.AbstractParser<MemberResponseDto>() {
    @java.lang.Override
    public MemberResponseDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MemberResponseDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MemberResponseDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MemberResponseDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.motaharinia.client.project.modules.member.rpc.stub.findbyid.MemberResponseDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

